package io.ffem.lite.common

object Constants {
    const val EXPECTED_QR_CORNER_COUNT = 4
    const val MAX_TILT_PERCENTAGE_ALLOWED = 0.016

    const val QR_TO_COLOR_AREA_DISTANCE_PERCENTAGE = 0.26
    const val CALIBRATION_COLOR_AREA_WIDTH_PERCENTAGE = 0.48

    const val IMAGE_THRESHOLD = 100
    const val MAX_COLOR_DISTANCE_RGB = 55
    const val MAX_COLOR_DISTANCE_CALIBRATION = 80
    const val DEFAULT_MINIMUM_BRIGHTNESS = 120
    const val DEFAULT_MAXIMUM_BRIGHTNESS = 240
    const val DEFAULT_SHADOW_TOLERANCE = 25
    const val INTERPOLATION_COUNT = 100.0
    const val MAX_DISTANCE = 999
}